config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  get "/dashboard", to: "pages#dashboard"

  resources :cryptos, only: [:index, :show]

  resources :favorites do
    resources :alerts
  end

  resources :platforms, only: [:index, :show]

  resources :exchangetimevalues, only: [:show, :new, :create, :edit, :update]

  resources :offers, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-wagon">
  <div class="footer-links-wagon" style="color:#f2efef">
    Made with CryptoCompare API
  </div>
  <div class="" style="color:#073F79">
     <i class="fa fa-registered" aria-hidden="true"></i> Crypt-easy
  </div>
</div>

app/views/shared/_navbar.html.erb
<header style="position: sticky; top:0px; z-index: 3">
<div class="navbar-wagon">
  <!-- Logo -->
  <% if user_signed_in? %>
  <%= link_to dashboard_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "crypteasy.png"%>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "crypteasy.png" %>
    <% end %>
  <% end %>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <%= link_to "Premium", offers_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Crypto-monnaies", cryptos_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>



    <!-- Profile picture with dropdown list -->
    <%= link_to destroy_user_session_path, method: :delete do %>
    <i class="fa fa-sign-out fa-lg btn-nav-lgo" aria-hidden="true"></i> <%= t(".sign_out", default: " ") %>
    <% end %>
    <% else %>
      <!-- Login link (when logged out) -->
    <%= link_to  t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-btn-login" %>

    <% end %>
  </div>
</header>