config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  get "/dashboard", to: "pages#dashboard"

  resources :cryptos, only: [:index, :show]

  resources :favorites do
    resources :alerts
  end

  resources :platforms, only: [:index, :show]

  resources :exchangetimevalues, only: [:show, :new, :create, :edit, :update]

  resources :offers, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :favorite
  belongs_to :user
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  def new
    @favorite = Favorite.find(params[:favorite_id])
    @alert = Alert.new
  end

  def create
    @alert = Alert.new(alert_params)
    @alert.favorite = Favorite.find(params[:favorite_id])
    @alert.user = current_user
    if @alert.save
      redirect_to favorite_alerts_path
    else
      render :new
    end
  end

  def show
    @alert = Alert.find(params[:id])
  end

  def index
    @alerts = Alert.where("favorite_id = '#{params[:favorite_id]}'")
  end

  def destroy

    Alert.find(params[:id]).destroy
    redirect_to favorite_alerts_path
  end

  def alert_params
    params.require(:alert).permit(:option, :price)
  end
end

app/views/alerts/index.html.erb
<div class="container">
  <div class="card-top">
    <div class="main-title text-center mt50 mb50">
      <h1 style="color: #053C7A;">Mes alertes actives</h1>
    </div>
  </div>
  <div class="col-sm-12">
    <div class="card-content pb20">
      <div id="data-table_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">

        <% if @alerts != [] %>

        <div class="row">
          <% if current_user.orders.where(state: 'paid') != [] %>
            <div class="text-right">
              <%= link_to new_favorite_alert_path(params[:favorite_id]) do %>
                <span class="btn"><i class="fa fa-plus" aria-hidden="true"></i>Ajouter une alerte</span>
              <% end %>
            </div>
          <% else %>
            <div class="text-right">
              <%= link_to offers_path, data: {confirm: "Vous devez être membre premium pour recevoir des alertes SMS."} do %>
                <span class="btn"><i class="fa fa-plus" aria-hidden="true"></i>Ajouter une alerte</span>
              <% end %>
            </div>
          <% end %>
          <table id="data-table" class="table table-striped table-bordered dataTable dtr-inline boxsha" cellspacing="0" width="100%" role="grid" aria-describedly="data-table_info" style="width: 100%; border: 2px solid rgb(220, 222, 226); text-align: center; background-color: white">
            <thead style="color: #053C7A;">
              <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="data-table" rowspan="1" colspan="1" style="width: 86px;" aria-label="Alert id: activate to sort column descending" aria-sort="ascending">
                  Alert id
                </th>
                <th class="sorting" tabindex="0" aria-controls="data-table" rowspan="1" colspan="1" style="width: 86px;" aria-label="Alert option: activate to sort column descending">
                  Option
                </th>
                <th class="sorting" tabindex="0" aria-controls="data-table" rowspan="1" colspan="1" style="width: 86px;" aria-label="Price: activate to sort column descending">
                  Price
                </th>
                <th class="sorting" tabindex="0" aria-controls="data-table" rowspan="1" colspan="1" style="width: 86px;" aria-label="Crypto Monnaie: activate to sort column descending">
                  Crypto
                </th>
                <th class="sorting" tabindex="0" aria-controls="data-table" rowspan="1" colspan="1" style="width: 86px;" aria-label="Platforme 1: activate to sort column descending">
                  Plateforme 1
                </th>
                <th class="sorting" tabindex="0" aria-controls="data-table" rowspan="1" colspan="1" style="width: 86px;" aria-label="Platforme 2: activate to sort column descending">
                  Plateforme 2
                </th>
                <th tabindex="0" aria-controls="data-table" rowspan="1" colspan="1" style="width: 86px;">
                  Supprimer
                </th>
              </tr>
            </thead>
            <tbody>
              <% @alerts.each do |alert| %>
                <tr role="row" class="odd">
                  <td><%= alert.id %></td>
                  <td><%= alert.option %></td>
                  <td><%= alert.price.to_s %></td>
                  <td><%= alert.favorite.crypto.name %></td>
                  <td><%= Platform.find(alert.favorite.platform1).name %></td>
                  <td><%= Platform.find(alert.favorite.platform2).name %></td>
                  <td>
                    <div class="text-center" style="margin-right: 5px;">
                      <%= link_to favorite_alert_path(favorite_id: alert.favorite.id, id: alert.id), method: :delete, data: {confirm: "Etes vous sur de vouloir supprimer cette alerte?"} do %>
                        <i class="fa fa-trash-o fa-lg" aria-hidden="true" style="color: gray"></i>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <% else %>

        <div class="col-sm-12">
          <div class="row mb50 mt50">
            <div class="col-sm-12">
              <div class="container cryptobox text-center" style="background-color: white;">
                <h3 style="color: #053C7A" class="mt30">
                  Vous n'avez pas encore créé d'alerte.
                </h3>
                <p>
                  Pour en ajouter il vous suffit de clicker sur
                  <% if current_user.orders.where(state: 'paid') != [] %>
                    <div class="">
                      <%= link_to new_favorite_alert_path(params[:favorite_id]) do %>
                        <span class="btn"><i class="fa fa-plus" aria-hidden="true"></i>Ajouter une alerte</span>
                      <% end %>
                    </div>
                  <% else %>
                    <div class="">
                      <%= link_to offers_path, data: {confirm: "Vous devez être membre premium pour recevoir des alertes SMS."} do %>
                        <span class="btn"><i class="fa fa-plus" aria-hidden="true"></i>Ajouter une alerte</span>
                      <% end %>
                    </div>
                  <% end %>
                </p>
                <div class="col-sm-12">
              <div class="row mb50">
                <div class="col-sm-2">
                  <i class="fa fa-info-circle fa-2x mt30" aria-hidden="true"></i>
                </div>
                <div class="col-sm-8">
                  <h5>
                    Pourquoi créer des alertes SMS?
                  </h5>
                  <p>
                    Les alertes vous permettent d’être prévenu immédiatement par SMS lorsque le cours de l’une de vos cryptomonnaie favorite, atteint une limite définie sur les plateformes selectionnées. </p>
                  <p>* L’utilisation de ce service nécéssite un abonnement. </p>
                  <p>** Une alerte est émise de façon unique. </p>
                </div>
              </div>
            </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/alerts/new.html.erb
<div class="container" style="height: 90vh;">
  <div class="layout-accounts">
    <div class="account-wrap">
      <div class="account-card">
        <div class="account-content smart-forms mt30">
          <%= link_to favorite_alerts_path(@favorite) do %>
            <span class="close text-right" style="margin-top: -20px">&times;</span>
          <% end %>
          <div class="text-center">
          </div>
          <div id="contact">
            <div class="form-body">
              <%= simple_form_for [@favorite, @alert] do |f| %>
                <div class="mt30 mb50">
                  <div class="tagline text-center" >
                      <h3 style="color: #073f79;">CREER UNE ALERTE</h3>
                  </div>
                </div>
                <div class="section colm colm6 mb30">
                  <%= f.input :option, label: "Je souhaite être informé si le prix du #{@favorite.crypto.name} est: ", collection: ["Superieur", "Inferieur"] %>
                </div>
                <div class="section colm colm6">
                  <%= f.input :price, label: "à" %>
                </div>
                <div class="form-footer mt50 mb30">
                  <%= f.submit "ENREGISTRER", class: "btn btn-primary btn-block" %>
                </div>
              <% end %>
              <div class="text-right">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>