config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  get "/dashboard", to: "pages#dashboard"

  resources :cryptos, only: [:index, :show]

  resources :favorites do
    resources :alerts
  end

  resources :platforms, only: [:index, :show]

  resources :exchangetimevalues, only: [:show, :new, :create, :edit, :update]

  resources :offers, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Payment for offer #{@order.offer_sku} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    user1 = @order.user
    number = user1.phone
    body = "#{charge.description} have been receive, enjoy your new CryptEasy experience"
    SendSmsService.new(number, body).send

    @order.update(payment: charge.to_json, state: 'paid')
    redirect_to dashboard_path

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

private

  def set_order
    @order = Order.where(state: 'pending').find(params[:order_id])
  end

end

app/views/payments/new.html.erb
<div class="container col-md-6 col-md-offset-3 cryptobox mt50 pb50", style="padding-left: 50px; background-color: #ffffff">
  <div class="main-title text-center">
    <h2>Rappel de la commande n°<%= @order.id %> : </h3>
  </div>
  <h5>
    Vous allez souscrire à l'abonnement "<%= @order.offer_sku %>",
  </h5>
  <h5>
    Son montant mensuel est de <%= humanized_money(@order.amount) %>.00€.
  </h5>
  <h5>
    L'offre s'activera immédiatement après récéption du paiement.
  </h5>
  <div class="col-md-12 pl30">
    <%= form_tag order_payments_path(@order) do %>
      <div class="pt50 text-center">
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="My Offer"
          data-email="<%= current_user.email %>"
          data-description="Offer <%= @order.offer_sku %>"
          data-amount="<%= @order.amount_cents %>"
          data-currency="<%= @order.amount.currency %>"></script>
      </div>
    <% end %>
  </div>
</div>