config/routes.rb
Rails.application.routes.draw do

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  get "/dashboard", to: "pages#dashboard"

  resources :cryptos, only: [:index, :show]

  resources :favorites do
    resources :alerts
  end

  resources :platforms, only: [:index, :show]

  resources :exchangetimevalues, only: [:show, :new, :create, :edit, :update]

  resources :offers, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end


end

app/models/crypto.rb
class Crypto < ApplicationRecord

  has_many :exchangetimevalues
  has_many :favorites

  validates :name, presence: true
  validates :accronym, presence: true


end

app/controllers/cryptos_controller.rb
require 'cryptocompare'

class CryptosController < ApplicationController
  def index

    @cryptos = Crypto.all
    @timevalues = Exchangetimevalue.where("platform_id = '3' AND crypto_id = '1'")
    @timevalues1 = Exchangetimevalue.where("platform_id = '2' AND crypto_id = '1'")
    @alltimevalues = []
    @alltimevalues1 = []
    @min = @timevalues[0].euro.to_f
    @max = @timevalues[0].euro.to_f
    @timevalues.each_with_index do |timeval, ind|
      @alltimevalues << [timeval.created_at.to_time.to_i,timeval.euro]
      @alltimevalues1 << [@timevalues1[ind].created_at.to_time.to_i, @timevalues1[ind].euro]
      # @alltimevalues << [ind+1,timeval.euro]
      if timeval.euro < @min
        @min = timeval.euro.to_f
      end
      if timeval.euro > @max
        @max = timeval.euro.to_f
      end
      @min = @min
      @max = @max

    end
        @testouille = @timevalues[0].created_at.utc.to_i
        @test1 = @timevalues[0].created_at


  end

  def show
    @crypto = Crypto.find(params[:id])
    if params[:platform]
      @timevalues = Exchangetimevalue.where("platform_id = '#{params[:platform]}' AND crypto_id = '#{params[:id]}'").last(300)
    else
      @timevalues = Exchangetimevalue.where("platform_id = '1' AND crypto_id = '#{params[:id]}'").last(300)
    end
    @alltimevalues = []
    @min = @timevalues[0].euro.to_f
    @max = @timevalues[0].euro.to_f
    @timevalues.each_with_index do |timeval, ind|
      @alltimevalues << [timeval.created_at.to_time.to_i * 1000,timeval.euro]
      if timeval.euro < @min
        @min = timeval.euro.to_f
      end
      if timeval.euro > @max
        @max = timeval.euro.to_f
      end
      @min = @min
      @max = @max
    end

        @timevalues1 = Exchangetimevalue.where("platform_id = '2' AND crypto_id = '#{params[:id]}'").last(300)
    @timevalues2 = Exchangetimevalue.where("platform_id = '3' AND crypto_id = '#{params[:id]}'").last(300)

        @alltimevalues1 = []
        @alltimevalues2 = []
        @min1 = @timevalues1[0].euro.to_f
        @max1 = @timevalues1[0].euro.to_f
        @min2 = @timevalues2[0].euro.to_f
        @max2 = @timevalues2[0].euro.to_f
    @timevalues1.each_with_index do |timeval, ind|
      @alltimevalues1 << [timeval.created_at.to_time.to_i * 1000,timeval.euro]
      if timeval.euro < @min1
          @min1 = timeval.euro.to_f
     end
     if timeval.euro > @max1
          @max1 = timeval.euro.to_f
     end

    end

    @timevalues2.each_with_index do |timeval, ind|
      @alltimevalues2 << [timeval.created_at.to_time.to_i * 1000,timeval.euro]
      if timeval.euro < @min2
          @min2 = timeval.euro.to_f
     end
     if timeval.euro > @max2
          @max2 = timeval.euro.to_f
     end

    end


    # Utilisé pour le calculateur sur la page crypto_show
    last_prices = []
    Platform.all.each do |platform|
      last_prices << [platform.id, Exchangetimevalue.where(crypto: params[:id], platform: platform).order(:created_at).last.euro]
    end

    @highest_price = last_prices.sort {|a,b| a[1] <=> b[1]}.last.last
    @highest_platform_id = last_prices.sort {|a,b| a[1] <=> b[1]}.last.first
    @lowest_price = last_prices.sort {|a,b| a[1] <=> b[1]}.first.last
    @lowest_platform_id = last_prices.sort {|a,b| a[1] <=> b[1]}.first.first

    @platform_low = Platform.find(@lowest_platform_id).name
    @platform_high = Platform.find(@highest_platform_id).name
  end
end

app/views/cryptos/index.html.erb
<div class="container mt40">
  <div class="main-title pt30 pb30">
    <h1>Crypto-monnaies</h1>
  </div>
  <div class="cryptobox">
    <div class="row" style="padding: 30px;">
      <% @cryptos.each do |crypto|%>
        <div class="col-xs-12 col-md-3 col-sm-4"">
          <div class="card-index-wagon">
            <div class="card-category-wagon">
              <img src="<%= crypto.photo_url %>", width="60">
            </div>
            <div class="card-description-wagon text-center">
              <%= crypto.name%>
            </div>
              <%= link_to crypto_path(crypto), :class => "card-link-wagon" do %>
                <div class="text-center crypto-title"></div>
              <% end %>
          </div>
        </div>
      <% end %>
          <div class="col-xs-12 col-md-3 col-sm-4">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://www.coingecko.com/assets/coin-250/monero-692618e262bdd111563bb0553d3e3fd3ae3b712d7833350c9dc4121c4b1d1c7d.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Monero
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://www.bitcoincash.org/img/bitcoincash-white.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            BitcoinCash
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://cdn.worldvectorlogo.com/logos/dash-3.svg", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Dash
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://www.datacoinz.com/wp-content/uploads/2017/11/Ripple.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Ripple
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://coincaptable.com/assets/images/coins/EOS.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            EOS
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://www.stellar.org/wp-content/themes/stellar/images/stellar-rocket-300.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Stellar Lumens
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://z.cash/theme/images/yellow-zcash-logo.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Zcash
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://cdn.worldvectorlogo.com/logos/nem-xem.svg", width="60">
          </div>
          <div class="card-description-wagon text-center">
            NEM
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://upload.wikimedia.org/wikipedia/en/0/0f/Ubiq_Logo.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Ubiq
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>

      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="http://allcoinsnews.com/wp-content/uploads/2017/03/logo-7.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Waves
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://www.cryptocoinsnews.com/wp-content/uploads/2014/02/vtc.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Vertcoin
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://www.coingecko.com/assets/coin-250/titcoin-03124a113833a8f4b072964ba7d7ac8bdddc12192d7e032056fca2803225b11d.png", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Titcoin
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3 col-sm-4"">
        <div class="card-index-wagon">
          <div class="card-category-wagon">
            <img src="https://www.okchanger.fr/cryptocurrency/preview-file/1727", width="60">
          </div>
          <div class="card-description-wagon text-center">
            Blackcoin
          </div>
          <%= link_to cryptos_path, :class => "card-link-wagon" do %>
            <div class="text-center crypto-title"></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>